language: elixir
matrix:
  include:
    - otp_release: 21.0
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 21.0
      elixir: 1.8
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, coveralls.travis"
after_script:
- "MIX_ENV=docs mix do deps.get, inch.report"
